Readded all changes
Geo-Mafia/Geo-Mafia pull request #112
Opened 2022-11-27 21:56 UTC by noahklowden

This should simply reimplement the changes to the game events done after #104 so that it can be readded.

2022-11-28 05:43 UTC, gypark23 commented
Have you ran this on tns run ios? The app immediately closes when you launch.

2022-11-28 05:45 UTC, noahklowden commented
> Have you ran this on tns run ios? The app immediately closes when you launch.
As I said in the meeting, I am not able to on my setup. I don't know which change seems to be causing the crash, then... Hm...

2022-11-28 05:48 UTC, Strongbrother1 commented
tns run ios crashes the program for me too, I'm not sure where though.

2022-11-28 05:49 UTC, gypark23 commented
> > Have you ran this on tns run ios? The app immediately closes when you launch.
> 
> As I said in the meeting, I am not able to on my setup. I don't know which change seems to be causing the crash, then... Hm...

The app closes right after the launch, so I am assuming that it is coming from the home component.ts. Though I am not really sure what is wrong with it...

2022-11-28 05:50 UTC, gypark23 commented
The new change didn't fix it FYI

2022-11-28 06:20 UTC, gypark23 commented
Still nope

2022-11-28 22:11 UTC, gypark23 requested changes

2022-11-28 22:11 UTC, gypark23 commented on appGeo/src/app/home/home.component.ts
> +    databaseAdd(GAMERULE_PATH, gameRules)
@noahklowden OK I just checked it, line 70 and line 72 are the source of errors. If you comment them out, the app runs.

2022-11-28 22:14 UTC, noahklowden commented on appGeo/src/app/home/home.component.ts
> +    databaseAdd(GAMERULE_PATH, gameRules)
Hm, alright. This is info that I need to pass through the database, though, so removing them is a temp fix, but... this won't work completely long term. Clearly I misinterpreted how the database works a bit

2022-11-28 22:15 UTC, noahklowden commented on appGeo/src/app/home/home.component.ts
> +    databaseAdd(GAMERULE_PATH, gameRules)
I'll test it a little more tonight. I've just about got tns run ios working on my laptop, finally

2022-11-29 03:32 UTC, gypark23 approved these changes

2022-11-29 03:55 UTC, merged